FROM zaquestion/sonarqube-scanner
# Unsure if we need to spawn 2 containers (qube and scanner)
# See  https://hub.docker.com/r/zaquestion/sonarqube-scanner and https://github.com/zaquestion/docker-sonarqube-python
# docker run -ti -v $(pwd):/root/src zaquestion/sonarqube-scanner and docker run -d -p 9000:9000 zaquestion/sonarqube-python ?