  # Docker compose file that has a java container that runs a GUI that spawns
  # sibling containers https://medium.com/@andreacolangelo/sibling-docker-container-2e664858f87a
version: '3.0'

services:
  java:
    build: ./src
    volumes:
    - ./src:/home
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - TERM=xterm
    - DISPLAY=192.168.0.20:0
    depends_on:
    - rstudio
    # - spyder
    - jupyter_notebook
    - markdown
    # - hadoop
    # - sonarqube_and_sonarscanner
    ports:
    - "8080:8080"
    # command: bash -c "docker run "
    command: bash -c "/usr/bin/docker pull tensorflow/tensorflow:latest && docker build -t git-image /home/git && docker pull sebmoule/docker-vscode && cd /home && sh run.sh"
    stdin_open: true
    tty: true

  rstudio:
    build: ./src/rstudio
    environment:
    - USER=rstudio
    - PASSWORD=qwerty
    ports:
    - "8787:8787"

  orange:
    image: acopar/orange-docker
    ports:
    - "6901:6901"
    
  jupyter_notebook:
    build: ./src/jupyter_notebook
    environment:
      - USER=root
      - PASSWORD=qwerty
    ports:
      - "8888:8888"

  markdown:
    build: ./src/markdown
    environment:
      - USER=root
      - PASSWORD=qwerty
    ports:
      - "12345:80"


# Mjd119 services
# Set variable from shell script here https://hub.docker.com/r/timcera/spyder-desktop-ubuntu

  # spyder:
  #   build: ./src/spyder
  #   volumes:
  #   - ./src:/home
  #   - /tmp/.X11-unix:/tmp/.X11-unix
  #   environment:
  #   - DISPLAY=:0
  #   - HHHOME=${HOME}
  # git: # Run docker run alpine/git <command like clone, pull, commit> <arguments>
  #   build: ./src/git
  #   volumes:
  #   - ./src:/root
  #   - $(pwd):/git
  #   - /tmp/.X11-unix:/tmp/.X11-unix
