  # Docker compose file that has a java container that runs a GUI that spawns
  # sibling containers https://medium.com/@andreacolangelo/sibling-docker-container-2e664858f87a
version: '3.0'

services:
  java:
    build: ./src
    volumes:
    - ./src:/home
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - TERM=xterm
    - DISPLAY=192.168.1.20:0
    depends_on:
    - rstudio
    - spyder
    - jupyter_notebook
    - markdown
    - vscode
    # - hadoop
    # - spark
    - sonarqube
    command: bash -c "/usr/bin/docker pull tensorflow/tensorflow:latest && docker build -t git-image /home/git && cd /home && sh run.sh"
    stdin_open: true
    tty: true

  rstudio:
    build: ./src/rstudio
    environment:
    - USER=rstudio
    - PASSWORD=qwerty
    ports:
    - "8787:8787"

  orange:
    image: acopar/orange-docker
    ports:
    - "6901:6901"
    
  jupyter_notebook:
    build: ./src/jupyter_notebook
    environment:
    - USER=root
    - PASSWORD=qwerty
    ports:
    - "8888:8888"

  markdown:
    build: ./src/markdown
    environment:
    - USER=root
    - PASSWORD=qwerty
    ports:
    - "12345:80"

# Solved path issue
# https://stackoverflow.com/questions/59904878/docker-compose-volume-name-is-too-short-names-should-be-at-least-two-alphanume
  vscode:
    image: codercom/code-server
    volumes: 
    - $PWD/:/home/coder/project
    user: "${UID}:${GID}"
    ports:
    - "8080:8080"

# Solved path issue
# https://stackoverflow.com/questions/59904878/docker-compose-volume-name-is-too-short-names-should-be-at-least-two-alphanume
  # Set variable from shell script here https://hub.docker.com/r/timcera/spyder-desktop-ubuntu
  spyder:
    image: timcera/spyder-desktop-ubuntu
    volumes:
    - ${HOME}/:/home/user
    - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY=192.168.0.20:0
    - HHHOME=${HOME}
    stdin_open: true
    tty: true

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
    - "9000:9000"
    - "9092:9092"
    
    