version: '3.0'

services:
  java:
    build: ./src
    volumes:
    - ./src:/home
    - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
    - rstudio
    ports:
    - "8080:8080"
    command: bash -c "cd /home && sh run.sh"

  rstudio:
    image: rocker/rstudio
    environment:
    - USER=rstudio
    - PASSWORD=qwerty
    ports:
    - "8787:8787"