version: '3.0'

services:
  java:
    build: ./src
    volumes:
    - ./src:/home
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - TERM=xterm
    - DISPLAY=192.168.0.201:0
    # depends_on:
    # - rstudio
    ports:
    - "8080:8080"
    # command: bash -c "docker run "
    command: bash -c "cd /home && sh run.sh"
    stdin_open: true 
    tty: true

  # rstudio:
  #   build: ./rstudio
  #   # image: rocker/rstudio
  #   environment:
  #   - USER=rstudio
  #   - PASSWORD=qwerty
  #   ports:
  #   - "8787:8787"