FROM acopar/orange-docker
# See https://hub.docker.com/r/acopar/orange-docker for how to run
# Open firefox to localhost:6901 on java container?
# docker run -p 127.0.0.1:5901:5901 -p 127.0.0.1:6901:6901 -it acopar/orange-docker