FROM singularities/spark
# Appears to require a docker-compose.yml file to spawn a master and worker (see dockerhub page)
# Open xterm to allow user to input commands aliased by Dockerfile of provided container?