FROM pvtmert/tableau
# Open firefox from java container to localhost:8850 (as specified by Dockerfile from provided container)?
# docker run --rm --privileged -itd -p8850:8850 -v/sys/fs/cgroup:/sys/fs/cgroup:ro pvtmert/tableau