FROM jupyter/base-notebook
# See https://jupyter-docker-stacks.readthedocs.io/en/latest/using/running.html#using-the-docker-cli for running
# Open firefox in java container to localhost and port number?