FROM exadra37/visual-studio-code
# https://gitlab.com/exadra37-dockerize-vscode/vscode-docker-cli/-/blob/master/docs/how-to/use.md says to run 'vscode' to open a new window
# Need to open xterm to run?