FROM timcera/spyder-desktop-ubuntu
# See dockerhub for shell script to start instance
# Other option also installs jupyter notebook but looks heavier (compdatasci/spyder-desktop)
# Run all commands from script straight from java function?